// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-SPlxgDfp0Cfu3LkaFcPJZh_7v23Pu_0',
    appId: '1:507627130402:web:a3a5aa6aec0959c590c47b',
    messagingSenderId: '507627130402',
    projectId: 'democracy-b4638',
    authDomain: 'democracy-b4638.firebaseapp.com',
    storageBucket: 'democracy-b4638.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx56NTd2ez7DllBXZPoe7Z6ahJjv7moP8',
    appId: '1:507627130402:android:971b7e8d1bc7b09e90c47b',
    messagingSenderId: '507627130402',
    projectId: 'democracy-b4638',
    storageBucket: 'democracy-b4638.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq_3FT_MxDgGjKKbS-IRynNBI9nRXTx-0',
    appId: '1:507627130402:ios:b9bf07eb9b6231d990c47b',
    messagingSenderId: '507627130402',
    projectId: 'democracy-b4638',
    storageBucket: 'democracy-b4638.appspot.com',
    iosClientId: '507627130402-u1qqa1vj5dfck37emko1aa6hpomo0qu1.apps.googleusercontent.com',
    iosBundleId: 'com.example.admin',
  );
}
